// This file is autogenerated by RunContentSourceMerger
import Foundation

public enum AllContentSourceProviders {
    public static var allContentSourceProviders = [
ContentSourceProvider(
    source: ContentSource(
        id: Identifier("swift-by-sundell"),
        name: "Swift by Sundell",
        rssUrl: URL(string: "https://swiftbysundell.com/rss")!,
        podcastUrl: nil,
        playlistUrl: nil,
        websiteUrl: nil
    ),
    enrich: { blogPost -> IndexableBlogPost in
        var blogPost = blogPost
        blogPost.author = Author(name: "John Sundell")
        return blogPost
    }
)

    ]
}
